<script src="{{ asset('web/js/jquery-3.2.1.min.js') }}"></script>
<script src="{{ asset('web/js/popper.min.js') }}"> </script>
<script src="{{ asset('web/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('web/vendor/jquery.cookie/jquery.cookie.js') }}"> </script>
<script src="{{ asset('web/vendor/@fancyapps/fancybox/jquery.fancybox.min.js') }}"></script>
<script src="{{ asset('web/js/front.js') }}"></script>
<script src="{{ asset('web/js/jquery.scrollTo.js') }}"></script>
<script src="{{ asset('web/js/jquery.nav.js') }}"></script>
<script src="{{ asset('web/js/jquery.prettyPhoto.js') }}"></script>
<script src="{{ asset('web/js/isotope.js') }}"></script>
<script src="{{ asset('web/js/jquery.flexslider.js') }}"></script>
<script src="{{ asset('web/js/inview.js') }}"></script>
<script src="{{ asset('web/js/custom.js') }}"></script>